### ISSUE TITLE
AttributeError: module 'subprocess' has no attribute 'CREATE_NO_WINDOW'

### ISSUE THREAD

**Issue by rg321** [jlw4049/AutomaticDemuxer#1]
![image](https://user-images.githubusercontent.com/16621631/190854504-0150bedf-8306-4438-bcbb-b95863ee6304.png)

**Comment by jessielw** [comment]
This command is only avaliable in Windows. Let me fix this. Thanks for the report!

**Comment by jessielw** [comment]
Update to the latest version and this should be resolved! 

`pip install --upgrade AutomaticDemuxer`

Please report back!
